import type { Dish } from '../types'

export const CITIES = [
  'Hyderabad',
  'Bangalore',
  'Mumbai',
  'Delhi',
  'Chennai',
  'Pune',
  'Nizamabad',
  'Warangal',
  'Vijayawada',
  'Vizag'
]

export const TRENDING_AREAS: Record<string, string[]> = {
  'Hyderabad': ['Gachibowli', 'Jubilee Hills', 'Banjara Hills', 'Madhapur', 'Hitech City'],
  'Bangalore': ['Indiranagar', 'Koramangala', 'Whitefield', 'HSR Layout'],
  'Nizamabad': ['Pragathi Nagar', 'Kanteshwar', 'Khaleelwadi', 'Armoor Road']
}

export const CRAVINGS = [
  { label: 'Spicy' },
  { label: 'BBQ' },
  { label: 'Burgers' },
  { label: 'Pizza' },
  { label: 'Biryani' },
  { label: 'South Indian' },
  { label: 'North Indian' },
  { label: 'Chinese' },
  { label: 'Fast Food' },
  { label: 'Healthy' },
  { label: 'Veg' },
  { label: 'Non Veg' },
  { label: 'Cafes' },
  { label: 'Desserts' },
  { label: 'Drinks' },
  { label: 'Romantic' },
  { label: 'Family Dining' },
  { label: 'Fine Dining' },
  { label: 'Chill Spot' },
  { label: 'Budget Friendly' }
]

export const DISH_TEMPLATES: Dish[] = [
  {
    id: 'dish-1',
    name: 'Special Butter Chicken',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=600&q=80',
    price: '₹320',
    discount: '15% OFF',
    restaurantName: 'Restaurant',
    isVeg: false,
    spiceLevel: 'Medium',
    popularTag: 'Bestseller',
    rating: 4.8,
    loveCount: 0,
    mustEatCount: 0,
    skipCount: 0
  },
  {
    id: 'dish-2',
    name: 'Double Cheese Margherita',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=600&q=80',
    price: '₹450',
    discount: '20% OFF',
    restaurantName: 'Restaurant',
    isVeg: true,
    spiceLevel: 'Mild',
    popularTag: 'Top Pick',
    rating: 4.7,
    loveCount: 0,
    mustEatCount: 0,
    skipCount: 0
  },
  {
    id: 'dish-3',
    name: 'Dum Claypot Biryani',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80',
    price: '₹380',
    discount: '10% OFF',
    restaurantName: 'Restaurant',
    isVeg: false,
    spiceLevel: 'Hot',
    popularTag: 'Spicy Special',
    rating: 4.9,
    loveCount: 0,
    mustEatCount: 0,
    skipCount: 0
  },
  {
    id: 'dish-4',
    name: 'Loaded Smashed Burger',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80',
    price: '₹240',
    discount: '25% OFF',
    restaurantName: 'Restaurant',
    isVeg: false,
    spiceLevel: 'Medium',
    popularTag: 'Trending #1',
    rating: 4.6,
    loveCount: 0,
    mustEatCount: 0,
    skipCount: 0
  },
  {
    id: 'dish-5',
    name: 'Spicy Ramen Bowl',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=600&q=80',
    price: '₹399',
    discount: '15% OFF',
    restaurantName: 'Restaurant',
    isVeg: false,
    spiceLevel: 'Insane',
    popularTag: 'Hot Pepper',
    rating: 4.8,
    loveCount: 0,
    mustEatCount: 0,
    skipCount: 0
  },
  {
    id: 'dish-6',
    name: 'Nutella Belgian Waffles',
    image: 'https://images.unsplash.com/photo-1562376502-6f769499c886?auto=format&fit=crop&w=600&q=80',
    price: '₹190',
    discount: '10% OFF',
    restaurantName: 'Restaurant',
    isVeg: true,
    spiceLevel: 'Mild',
    popularTag: 'Sweet Treat',
    rating: 4.5,
    loveCount: 0,
    mustEatCount: 0,
    skipCount: 0
  },
  {
    id: 'dish-7',
    name: 'Crispy Salmon Roll',
    image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=600&q=80',
    price: '₹420',
    discount: 'Free Miso Soup',
    restaurantName: 'Restaurant',
    isVeg: false,
    spiceLevel: 'Mild',
    popularTag: 'Chef Special',
    rating: 4.7,
    loveCount: 0,
    mustEatCount: 0,
    skipCount: 0
  },
  {
    id: 'dish-8',
    name: 'Paneer Butter Masala',
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?auto=format&fit=crop&w=600&q=80',
    price: '₹280',
    discount: '15% OFF',
    restaurantName: 'Restaurant',
    isVeg: true,
    spiceLevel: 'Medium',
    popularTag: 'Bestseller',
    rating: 4.6,
    loveCount: 0,
    mustEatCount: 0,
    skipCount: 0
  },
  {
    id: 'dish-9',
    name: 'Peri Peri Loaded Fries',
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=600&q=80',
    price: '₹160',
    discount: 'Buy 1 Get 1',
    restaurantName: 'Restaurant',
    isVeg: true,
    spiceLevel: 'Hot',
    popularTag: 'Party Snack',
    rating: 4.4,
    loveCount: 0,
    mustEatCount: 0,
    skipCount: 0
  },
  {
    id: 'dish-10',
    name: 'Ghee Roast Dosa',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80',
    price: '₹140',
    discount: '10% OFF',
    restaurantName: 'Restaurant',
    isVeg: true,
    spiceLevel: 'Mild',
    popularTag: 'Morning Special',
    rating: 4.5,
    loveCount: 0,
    mustEatCount: 0,
    skipCount: 0
  },
  {
    id: 'dish-11',
    name: 'Avocado Quinoa Salad',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=600&q=80',
    price: '₹290',
    discount: '15% OFF',
    restaurantName: 'Restaurant',
    isVeg: true,
    spiceLevel: 'Mild',
    popularTag: 'Healthy Choice',
    rating: 4.3,
    loveCount: 0,
    mustEatCount: 0,
    skipCount: 0
  },
  {
    id: 'dish-12',
    name: 'Chilli Garlic Noodles',
    image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=600&q=80',
    price: '₹220',
    discount: '10% OFF',
    restaurantName: 'Restaurant',
    isVeg: true,
    spiceLevel: 'Hot',
    popularTag: 'Hot Wok',
    rating: 4.5,
    loveCount: 0,
    mustEatCount: 0,
    skipCount: 0
  },
  {
    id: 'dish-13',
    name: 'Sizzling Chocolate Brownie',
    image: 'https://images.unsplash.com/photo-1508737027454-e6454ef45afd?auto=format&fit=crop&w=600&q=80',
    price: '₹210',
    discount: '15% OFF',
    restaurantName: 'Restaurant',
    isVeg: true,
    spiceLevel: 'Mild',
    popularTag: 'Must Try',
    rating: 4.8,
    loveCount: 0,
    mustEatCount: 0,
    skipCount: 0
  },
  {
    id: 'dish-14',
    name: 'Crispy Momos',
    image: 'https://images.unsplash.com/photo-1626132647523-66f5bf380027?auto=format&fit=crop&w=600&q=80',
    price: '₹150',
    discount: 'Buy 1 Get 1',
    restaurantName: 'Restaurant',
    isVeg: true,
    spiceLevel: 'Medium',
    popularTag: 'Street Star',
    rating: 4.6,
    loveCount: 0,
    mustEatCount: 0,
    skipCount: 0
  },
  {
    id: 'dish-15',
    name: 'Paneer Tikka Roll',
    image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=600&q=80',
    price: '₹180',
    discount: '10% OFF',
    restaurantName: 'Restaurant',
    isVeg: true,
    spiceLevel: 'Medium',
    rating: 4.5,
    loveCount: 0,
    mustEatCount: 0,
    skipCount: 0
  },
  {
    id: 'dish-16',
    name: 'Red Velvet Pastry',
    image: 'https://images.unsplash.com/photo-1498804103079-a6351b050096?auto=format&fit=crop&w=600&q=80',
    price: '₹140',
    discount: '15% OFF',
    restaurantName: 'Restaurant',
    isVeg: true,
    spiceLevel: 'Mild',
    rating: 4.4,
    loveCount: 0,
    mustEatCount: 0,
    skipCount: 0
  },
  {
    id: 'dish-17',
    name: 'Szechuan Chicken Wings',
    image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=600&q=80',
    price: '₹260',
    discount: '20% OFF',
    restaurantName: 'Restaurant',
    isVeg: false,
    spiceLevel: 'Insane',
    popularTag: 'Spicy Signature',
    rating: 4.7,
    loveCount: 0,
    mustEatCount: 0,
    skipCount: 0
  },
  {
    id: 'dish-18',
    name: 'Stuffed Garlic Bread',
    image: 'https://images.unsplash.com/photo-1590947132387-155cc02f3212?auto=format&fit=crop&w=600&q=80',
    price: '₹199',
    discount: '10% OFF',
    restaurantName: 'Restaurant',
    isVeg: true,
    spiceLevel: 'Mild',
    rating: 4.5,
    loveCount: 0,
    mustEatCount: 0,
    skipCount: 0
  },
  {
    id: 'dish-19',
    name: 'Classic Cold Coffee',
    image: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=600&q=80',
    price: '₹150',
    discount: 'Buy 2 Get 1 Free',
    restaurantName: 'Restaurant',
    isVeg: true,
    spiceLevel: 'Mild',
    rating: 4.6,
    loveCount: 0,
    mustEatCount: 0,
    skipCount: 0
  },
  {
    id: 'dish-20',
    name: 'Dal Makhani Combo',
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?auto=format&fit=crop&w=600&q=80',
    price: '₹299',
    discount: '15% OFF',
    restaurantName: 'Restaurant',
    isVeg: true,
    spiceLevel: 'Medium',
    rating: 4.6,
    loveCount: 0,
    mustEatCount: 0,
    skipCount: 0
  }
]
